### ISSUE TITLE
关于定时任务

### ISSUE THREAD

**Issue by BnqDzj** [DustinWin/clash-tools#2]
定时任务里的定时更新 Clash.Meta 内核要先 /data/clash/start.sh stop 停止了才能替换
不然Curl会报错，无法替换
![image](https://github.com/DustinWin/clash-tools/assets/64721413/20b1bd6b-01a9-4d22-9863-8baab5bac287)
即改成
`30 3 * * * /data/clash/start.sh stop && curl -o /data/clash/clash -L https://cdn.jsdelivr.net/gh/DustinWin/clash-tools@main/Clash.Meta-release/clash.meta-linux-armv8 && chmod +x /data/clash/clash && /data/clash/start.sh restart >/dev/null 2>&1 #每天早上 3 点半更新 Clash.Meta 内核`

**Comment by DustinWin** [comment]
什么设备？我这边的路由器不会遇到该问题。

**Comment by DustinWin** [comment]
> > 什么设备？我这边的路由器不会遇到该问题。
> 
> 用的VPS
> 
> 系统是 Debian GNU/Linux 12 x86_64
> 
> AdGuard的更新也需要先停止才能更

> > 什么设备？我这边的路由器不会遇到该问题。
> 
> 用的VPS
> 
> 系统是 Debian GNU/Linux 12 x86_64
> 
> AdGuard的更新也需要先停止才能更新

添加一个命令 `chmod 644 /data/clash/clash` 试试。

**Comment by DustinWin** [comment]
> ![Screenshot_2023-10-10-14-03-20-602_com microsoft emmx-edit](https://user-images.githubusercontent.com/64721413/273792435-55e29ae4-1876-464a-87bd-3a71ea6ed757.jpg)
> 
> ![Screenshot_2023-10-10-14-02-57-848_com sonelli juicessh-edit](https://user-images.githubusercontent.com/64721413/273792429-d68744d1-7203-4302-8d15-e3f236a50b1b.jpg)
> 
> 设置644了，还是不行 建议在文档里加上先停止的命令，以避免这种情况

把“写入”也加上。
